# Generated by Django 6.0.3 on 2026-05-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='chief_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_balance',
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_department', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Expert', 'Expert')], default='Junior', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='leavingrequests',
            name='type',
            field=models.CharField(choices=[('Annual Leave', 'Annual'), ('Sick Leave', 'Sick')], default='Annual Leave', max_length=100),
        ),
    ]
