# Generated by Django 6.0.3 on 2026-05-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_department_chief_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavingrequests',
            name='end_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leavingrequests',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavingrequests',
            name='start_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leavingrequests',
            name='type',
            field=models.CharField(choices=[('Annual Leave', 'Annual'), ('Sick Leave', 'Sick'), ('Personal Leave', 'Personal'), ('Maternity', 'Maternity')], default='Annual Leave', max_length=100),
        ),
    ]
